CREATE TABLE `jobOffers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`company` varchar(255) NOT NULL,
	`source` varchar(100) NOT NULL,
	`sourceUrl` text NOT NULL,
	`location` varchar(160) NOT NULL,
	`modality` enum('Presencial','Híbrido','Remoto','Flexible') NOT NULL,
	`contractType` varchar(120) NOT NULL,
	`area` varchar(160) NOT NULL,
	`publishedAt` timestamp,
	`salary` varchar(120),
	`description` text NOT NULL,
	`requirements` text NOT NULL,
	`applicationStatus` enum('pendiente','favorita','aplicada','descartada') NOT NULL DEFAULT 'pendiente',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobOffers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jobProfiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`headline` varchar(255) NOT NULL,
	`summary` text NOT NULL,
	`skills` text NOT NULL,
	`desiredRoles` text NOT NULL,
	`targetAreas` text NOT NULL,
	`locations` text NOT NULL,
	`modalities` text NOT NULL,
	`contractTypes` text NOT NULL,
	`languages` text NOT NULL,
	`keywords` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobProfiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `jobProfiles_userId_unique` UNIQUE(`userId`)
);
